language: python
python:
  - 3.7

os: linux
dist: xenial
sudo: required

git:
  depth: 20

cache:
  apt: true
  pip: true

env:
  global:
    - OMP_NUM_THREADS=1

before_install:
  - sudo apt-get -qq install libopenmpi-dev openmpi-bin
  - pip3 install pyscf mpi4py pytest-cov

install:
  - pip3 install .

script:
  #- mpiexec -np 1 tests/runtests.sh
  - echo 'scf_hf_BLKSIZE_MIN = 4' > pyscf_config.py
  - PYSCF_CONFIG_FILE=$(pwd)/pyscf_config.py
    mpiexec -np 2 tests/runtests.sh
